site_name: FPGA Notes
site_url: https://sebram99.github.io/fpgawebpage/
nav:
    - Introduction: index.md
    - Test Bench Notes: TestBenchNotes.md
    - VUnit Test Framework Notes: VUnitTestFramework.md

theme: readthedocs