site_name: FPGA & SDR
site_url: https://sebram99.github.io/fpgawebpage/
nav:
    - Introduction: index.md
    - Utilities: Utilities.md
    - Blog:
      - blog/index.md

theme: material

plugins:
  - blog